server:
  port: 8087
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
ribbon:
  ReadTimeout: 3000 # 调用服务超时时间
  ConnectTimeout: 3000 # A调用B 链接服务的超时时间