server:
  port: 8083
spring:
  application:
    name: provider

eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}